### PR TITLE
Assignment 2 - Kristof Rabay

### PR DESCRIPTION
**Pull request by kristofrabay**
Submitting Part 2 and 3 of assignment 2.  To my understanding Part 4 and 5 do not need to be pushed to GitHub, only the discourse tasks need to be completed. On a separate note, I was able to push Rmd files to GitHUb from R studio, but not html files (or pdfs, i'm assuming) so had to do that part from Git Bash. (good practice, but is there something maybe i'm missing in R studio that would let me commit and push other files than rmd? did not really get usable input from googling)

### CODE REVIEW

**Comment by julcsii** [comment]
Were there any error messages or logs in RStudio?

I tried to reproduce the problem, but  I could not. It worked for me to push html, pdf and other file types to remote from RStudio.

**Comment by kristofrabay** [comment]
No error messages, simply when I was in the "commiting window" (sorry for the amateur naming) I could not see it, could not attach it. Even git didn't want to add them at first:

(The following paths are ignored by one of your .gitignore files:
lecture1/lecture1-to-fill-in_Kristof_Rabay.html
Use -f if you really want to add them.)

So by using add -f it worked. But I'm sure R Studio allows me to do it, it seems such a basic task. 

Can you recommend anything (maybe something hasn't installed, I messed up some setting, etc..)?

**Comment by julcsii** [comment]
The reason why you could not add and commit the files probably lies with the `.gitigore` file. This is a file that specifies certain rules on what kind of files, folders to exclude from tracking with git. Usually we exclude local settings of IDEs such as RStudio and some cases large data files or sensitive files.

If you look at the `.gitignore` file in the repo, you'll notice that it actually excludes htmls, pdfs from git on purpose:

```
# Don't track output files (html, pdf, ...)
**/*.pdf
**/*.html
**/*.docx
**/*.log
```

Are you sure you want to commit such files?

**Comment by kristofrabay** [comment]
Thank you! And it is even obvious in the error message..  I must have glanced over it late night.. But thank you for pointing that out! Whenever I'll have to commit files as such I will temporarily 'unblock' them

**Comment by MarcKaufmann** [comment]
I assume that you tried to push to the main repository by error, rather than to your own? I'm closing this request, as I don't want your home assignment to overrule my files.

**Comment by kristofrabay** [comment]
Yes, sorry for that!

**Comment by MarcKaufmann** [comment]
No worries.

**Pull request closed without merging**
